project_id = "gzsfdghxiuhpgwdfwegj"

[functions.health]
verify_jwt = false

[functions.whatsapp-webhook]  
verify_jwt = false

[functions.flutterwave-webhook]
verify_jwt = false

[functions.payment-success]
verify_jwt = false

[functions.cleanup-sessions]
verify_jwt = false