// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzsfdghxiuhpgwdfwegj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6c2ZkZ2h4aXVocGd3ZGZ3ZWdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTM4NDQsImV4cCI6MjA3MDY4OTg0NH0.aZowduMWulWknG1FPZdJQTxmcRKjigs0U90v8oYfA6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});